#include <rpc/rpc.h>
#include "avg.h"
#include <stdio.h>

/* run locally on 'server' called by a remote client. */
//static double sum_avg;
static stat statValue;

int cmpfunc (const void * a, const void * b) {
  return ( *(double*)a - *(double*)b );
}

stat * stat_1(input_data *input, CLIENT *client) {
  double average;
  double mode;
  double median;
  /* input is paramters were marshalled by genrated routine */
  /*  a pointer to a double, is set to begining of data array  */
  double *dp = input->input_data.input_data_val;

  u_int i;
  average = 0;
  double numbers[input->input_data.input_data_len];
  for( i = 1; i <= input->input_data.input_data_len; i++ ){
    numbers[i-1] = *dp;
    average += *dp;
    dp++;
  }
  // sort the array
  qsort(numbers,input->input_data.input_data_len,sizeof(double),cmpfunc);
  
  // get average
  average /= input->input_data.input_data_len;

  // get median
  int halfIndex = input->input_data.input_data_len/2;
  if(input->input_data.input_data_len%2 == 0){
    median = ((double)numbers[halfIndex-1] + (double)numbers[halfIndex])/2;
  }else{
    median = numbers[halfIndex];
  }

  //mode
   mode = numbers[0];
  int lastMode = mode;
  int count = 1;
  int maxCount = 1;
  for(int i = 1; i < input->input_data.input_data_len; i++){
    if(lastMode == numbers[i]){
      count++;
    }else{
      count = 1;
      lastMode = numbers[i];
    }
    if(count > maxCount){
      maxCount = count;
      mode = lastMode;
    }
  }  
  statValue.average = average;
  statValue.median = median;
  statValue.mode = mode;
  
  return( &statValue );
}

/* 
 * server stub 'average_1_svc function handle called in avg_svc that was
 * generated by rpcgen 
 * FYI:
 *   result = (*local)((char *)&argument, rqstp);
 *   where local is (char *(*)(char *, struct svc_req *)) average_1_svc;
 */
 
stat * stat_1_svc(input_data *input, struct svc_req *svc) {
  CLIENT *client;
  return( stat_1( input, client) );
 }
