/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _AVG_H_RPCGEN
#define _AVG_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAXAVGSIZE 200

struct input_data {
	char text[200];
};
typedef struct input_data input_data;

struct input_data_echo {
	char text_echo[200];
};
typedef struct input_data_echo input_data_echo;

#define ECHO_PROGS 21500
#define ECHO_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define ECHO 1
extern  input_data_echo * echo_1(input_data *, CLIENT *);
extern  input_data_echo * echo_1_svc(input_data *, struct svc_req *);
extern int echo_progs_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define ECHO 1
extern  input_data_echo * echo_1();
extern  input_data_echo * echo_1_svc();
extern int echo_progs_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_input_data (XDR *, input_data*);
extern  bool_t xdr_input_data_echo (XDR *, input_data_echo*);

#else /* K&R C */
extern bool_t xdr_input_data ();
extern bool_t xdr_input_data_echo ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_AVG_H_RPCGEN */
