#include <rpc/rpc.h>
#include "avg.h"
#include <stdio.h>

/* run locally on 'server' called by a remote client. */
//static double sum_avg;
static input_data listData;

int ascending (const void * a, const void * b) {
  double da = *(double *) a;
  double db = *(double *) b;
  return (da > db) ? 1 : -1;
}

int descending (const void * a, const void * b) {
  double da = *(double *) a;
  double db = *(double *) b;
  return (da < db) ? 1 : -1;
}

input_data * list_1(input_data *input, CLIENT *client) {
  /* input is paramters were marshalled by genrated routine */
  /*  a pointer to a double, is set to begining of data array  */
  double *dp = input->input_data.input_data_val;
  double f;
  u_int i;
  double numbers[(input->input_data.input_data_len)-1];
  // skip the first element because it is -a or -d
  int order = *dp;
  dp++;
  // add all element to the array
  for( i = 0; i < (input->input_data.input_data_len)-1; i++ ){
    numbers[i] = *dp;
    dp++;
  }
  
  // sort the array
  if(order == 0){
    qsort(numbers,input->input_data.input_data_len-1,sizeof(double),ascending);
  }else{
    qsort(numbers,input->input_data.input_data_len-1,sizeof(double),descending);
  }
  
  listData.input_data.input_data_val = (double*) malloc(MAXAVGSIZE*sizeof(double));
  /* pointer to double, beginning of input data */
  dp = listData.input_data.input_data_val;
  /* set number of items */
  listData.input_data.input_data_len = (input->input_data.input_data_len)-1;

  for( i = 0; i < listData.input_data.input_data_len; i++ )
    {
      f = numbers[i];
      *dp = f;
      dp++;
    }

  return( &listData );
}

/* 
 * server stub 'average_1_svc function handle called in avg_svc that was
 * generated by rpcgen 
 * FYI:
 *   result = (*local)((char *)&argument, rqstp);
 *   where local is (char *(*)(char *, struct svc_req *)) average_1_svc;
 */
 
input_data * list_1_svc(input_data *input, struct svc_req *svc) {
  CLIENT *client;
  return( list_1( input, client) );
 }
