#include "avg.h"	/* header file generated by rpcgen */ 
#include <stdlib.h>


/* local routine client */
/* prototype can be whatever you want */
void stat_progs_1( char* host, int argc, char *argv[])
{
   CLIENT *clnt; /* client handle, rpc.h included in avg.h from rpcgen */
   int i;
   double f, *dp;
   input_data *listData;
   char *endptr;
   input_data  list_1_arg; /* input_data rpc struct */

   list_1_arg.input_data.input_data_val = (double*) malloc(MAXAVGSIZE*sizeof(double));

   /* pointer to double, beginning of input data */
   dp = list_1_arg.input_data.input_data_val;
   
   /* set number of items */
   list_1_arg.input_data.input_data_len = argc - 2;
   for( i = 1; i <= (argc - 2); i++ ){
     if(i == 1){
       if(strcmp(argv[2], "-a") == 0){
	 f = 0;
       }else{
	 f = 1;
       }
       *dp = f;
       dp++;
     }else{
       /* str to d ASCII string to floating point nubmer */
       f = strtod( argv[i+1], &endptr);
       *dp = f;
       dp++;
     }
   }


   /*  clnt_create(host, program, version, protocol)
    * generic client create routine from rpc library * * program = AVERAGEPROG is the number 22855 
    * version = AVERAGEVERS is 1
    * transfer protocol 
    *
    * defined by application programmer in avg.x and  then
    * these definitions in turn are generated into avg.h 
    * udp is of-course the user datagram protocol 
    *
    * returns a client RPC handle
    */

   clnt = clnt_create( host, STAT_PROGS, STAT_VERS, "udp" );

   /* check if error */
   if (clnt == NULL) 
   {
      /* 
       * rpc error library routine
       *  print a more descriptive error 
       */
   
      clnt_pcreateerror( host );
      exit(1);
   }


   /* now call average routine 'just' like a local routine 
    * but this will now go over network 
    * average_1 is definined in the client stub 
    * avg_clnt.c  that was generated by rpcgen
    * send in ptr to the parameters or args  in first field, and 
    * client handle in second field (created in clnt_create ) 
    * average_1 ultimately calls clnt_call() macro see man rpc
    *  than calls the remote routine associated with the client handle
    * so AVERAGEPROG, VERSION 
    */

   //print the sorted list
   listData = list_1( &list_1_arg, clnt );
   
   if (listData == NULL){
     clnt_perror(clnt, "call failed:");
   }
   
   /* pointer to double, beginning of input data */
   dp = listData->input_data.input_data_val;
   
   printf("value:");
   for( i = 0; i < listData->input_data.input_data_len; i++ )
   {
        f = *dp;
	printf("%f ",f);
        dp++;
   }
   printf("\n");
   
   clnt_destroy( clnt );
}


/* here is main */
int main( int argc, char* argv[] )
{
   char *host;

   /* check correct syntax */
   if(!(strcmp(argv[2], "-a") == 0 || strcmp(argv[2], "-d") == 0) ||  argc < 4 ){
     	printf( "usage: %s server_host (-a or -d) value ...\n", argv[0]); 
     	exit(1);
   }
   if( argc > MAXAVGSIZE + 3 ){
   	printf("Two many input values\n");
    	exit(2);
   }

   /* host name is in first parameter (after program name) */
   host = argv[1];
   stat_progs_1( host, argc, argv);
   exit(0);
}
